name: Upload backend 

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - run: |
           npm install
           npm run build 
           ls
           pwd
          
           

